CREATE TABLE AssocRegimeEnfant(
          LOGIN VARCHAR(7),
          PRENOM VARCHAR(20),
          REGIME VARCHAR(25),
          PRIMARY KEY(LOGIN, PRENOM, REGIME),
          FOREIGN KEY(LOGIN, PRENOM) REFERENCES TENFANT(LOGIN, PRENOM),
          FOREIGN KEY(REGIME) REFERENCES TREGIME(REGIME)
);